;
; This file is distributed under the MIT License. See LICENSE.md for details.
;
; Eligibility is initially computed from the unflattened helper bodies.
; SlimDown's always-inliner exposes a runtime GEP in the outer helper. Refresh
; the policy after linking the transformed helpers, before inlining callers.
;
; RUN: %root/bin/revng opt -enable-new-pm=0 -detect-uninlinable-helpers -verify %s -o %t.full.bc
; RUN: %root/bin/revng opt -enable-new-pm=0 -slim-down-helpers-module -sroa -instsimplify -simplifycfg -strip-dead-debug-info -verify %t.full.bc -S -o %t.slim.ll
; RUN: FileCheck %s --check-prefix=SLIM < %t.slim.ll
; RUN: llvm-link %t.slim.ll %S/Inputs/helper-policy-refresh-caller.ll -o %t.linked.bc
; RUN: %root/bin/revng opt -enable-new-pm=0 -mem2reg -link-helpers-to-inline -detect-uninlinable-helpers -inline-helpers -delete-helper-bodies -verify %t.linked.bc -S -o - | FileCheck %s
;
; SLIM: define i32 @read_runtime_index() section "revng_inline" !revng.inline.policy ![[POLICY:[0-9]+]]
; SLIM: getelementptr [4 x i32], ptr @values, i32 0, i32 %index
; SLIM-DAG: ![[POLICY]] = !{i1 false}
;
; CHECK-LABEL: define i32 @runtime_export()
; CHECK-NOT: getelementptr
; CHECK: call i32 @read_runtime_index()
; CHECK-NOT: getelementptr
; CHECK: ret i32
; CHECK-LABEL: define i32 @arithmetic_export(i32 %input)
; CHECK-NOT: call
; CHECK: add i32 %input, 1
; CHECK-NOT: call
; CHECK: ret i32
;
; Entirely synthetic helper bundle. Policies are generated by the detector.
target datalayout = "e-m:e-p:32:32-i64:64-n8:16:32-S128"
target triple = "i386-unknown-linux-gnu"
!revng.qemu_architecture = !{!0}
!0 = !{!"i386"}

@values = internal constant [4 x i32] [i32 5, i32 9, i32 13, i32 17]
@runtime_index = global i32 0

define i32 @read_table(i32 %index) section "revng_inline" {
  %address = getelementptr [4 x i32], ptr @values, i32 0, i32 %index
  %value = load i32, ptr %address, align 4
  ret i32 %value
}

define i32 @read_runtime_index() section "revng_inline" {
  %index = load i32, ptr @runtime_index, align 4
  %value = call i32 @read_table(i32 %index)
  ret i32 %value
}

define i32 @add_one(i32 %input) section "revng_inline" {
  %result = add i32 %input, 1
  ret i32 %result
}
